package main

//import "github.com/davecgh/go-spew/spew"
import (
	"./alignment"
	s "./scorehandler"
	"./scorehandler/blosum62"
	a "./types/amino"
	n "./types/nucleic"
	"fmt"
	"github.com/davecheney/profile"
	"time"
)

func test(scoreHandler s.ScoreHandler) *alignment.Alignment {
	cmp := alignment.NewAlignment(
		//[]n.NucleicAcid{n.G, n.C, n.G, n.A, n.T, n.G, n.A, n.G, n.C, n.T, n.T, n.G},
		//[]a.AminoAcid{a.M, a.R, a.A, a.C},
		//[]n.NucleicAcid{n.C, n.C, n.T, n.C, n.A, n.A, n.A, n.T, n.C, n.T, n.A, n.G, n.T, n.C, n.T, n.T, n.T, n.G, n.G, n.C},
		//[]a.AminoAcid{a.P, a.Q, a.I, a.T, a.L, a.W},
		//n.ReadString( /*"CCT*/ "CAAATCACTCTTTGGCAACGACCCATCGTCACAATAAAGATAGGGGGGCAGCTAARGGAAGCTCTATTAGATACAGGAGCAGATGATACAGTATTAGAAGATATAAATTTGCCAGGAAGATGGACACCAAAAATKATAGTGGGAATTGGAGGTTTTACCAAAGTAAGACAGTATGATCAGATACCTGTAGAAATTTGTGGACATAAAGCTATAGGTACAGTRTTAGTAGGACCTACACCTGCCAACATAATTGGAAGAAATCTGTTGACYCAGATTGGTTGCACTTTAAATTTT"+"CCNAT*AGTCCTATTGACACTGTACCAGTAAAATTAAAGCCAGGAATGGATGGCCCAAAAGTTAAACAATGGCCATTGACAGAAGAAAAAATAAAAGCATTAGTAGAAATTTGTGCAGAATTGGAASAGGACGGGAAAATTTCAAAAATTGGGCCTGAAAATCCATACAATACTCCAGTATTTGCCATAAAGAAAAAGAACAGYGATAAATGGAGAAAATTAGTAGATTTCAGAGAACTTAATAAGAGAACTCAAGACTTCTGGGAAGTTCAATTAGGAATACCACATCCCGGAGGGTTAAAAAAGAACAAATCAGTAACAGTACTGGATGTGGGTGATGCATATTTTTCARTTCCCTTAGATGAAGACTTCAGGAAGTATACTGCATTTACCATACCTAGTATAAACAATGAGACACCAGGGACTAGATATCAGTACAATGTGCTTCCACAGGGATGGAAAGGATCACCAGCAATATTCCAAAGTAGCATGACAAGAATCTTAGAACCTTTTAGAAAACAGAATCCAGACATAGTTATCTGTCAATAYGTGGATGATTTGTATGTAGGATCTGACTTAGAAATAGAGMAGCATAGAACAAAAGTAGAGGAACTGAGACAACATTTGTGGAAGTGGGGNACACACCAGACAAMAAACATCAGAAAGAACCTCCATTCCTTTGGATGGGTTATGAACTCCATCCTGATAAATGGACA"+"GCTTAATAGTGA"),
		n.ReadString("CCTCAGATCACTCTTTGGCAACGACCCTTCGTCAAYATAAAGATAGGGGGGCAAACAATAGAAGCTCTATTAGATACAGGAGCAGATGATACAGTATTAGAAGACATAGATTTGCCAGGAAGATGGAAGCCAAAAATGATAGGGGGAATTGGAGGTTTTATCAAAGTAAAACAGTATGATCAGGTACCCATAGAAATCTGTGGACATAAAGTTATAGGTACAGTATTAGTAGGACCTACACCTGTCAACGTAATTGGAAGAAATCTGATGACTCGGATTGGTTGCACTTTAAATTTTC" /*C*/ +"G"+"CATTAGTCCTATTGAMACTGTACCAGTAAAATTAAAGCCAGGAATGGATGGGCCAAAAGTTAAACAATGGCCATTGACAGAAGAAAAAATAAAAGCATTAGAAGAAATTTGTGCAGAATTGGAAAAGGAAGGAAAAATTTCAAAAATTGGGCCTGAAAATCCATACAATACTCCAGTATTTGCCATAAAGAAAAAAGAAAGTAGTAGTGGTAAATGGAGAAAATTAGTAGATTTTAGAGAACTTAATAAGAGAACTCAAGATTTCTGTGAAGTTCAATTAGGAATACCACATCCCGCAGGGTTAAAAAAGAAAAAGTCAGTAACAGTACTGGATGTGGGTGATGCATATTTTTCAGTTCCCTTAGATGAAGACTTCAGGAAGTATACTGCATTTACCATACCTAGTACAAACAATGAGACACCAGGAACTAGGTATCAGTACAATGTGCTTCCACAGGGATGGAAA"+"AA"+"GGATCACCAGCAATATTCCAAGCTAGCATGACAAAAATCTTAGAGCCTTTCAGAAAGCAAAAYCCAGACATAGTTATCTATCAATACATGGATGATTTGTATGTAGGMTCTGACTTAGAAATAGGGCAGCATAGAACAAAAATAGAGGAATTAAGAGAACATCTGCTRAGGTGGGGATTTTACACACCAGACAAAAAACATCAGAAAGAACCTCCATTCGGATGGGCTATGAACTCCATCCTGATAAATGGACAGTGCAGCCTATWGTGCTGCCAGAAAAAGACAGCTGGA" /*C*/ +"A"+"TT"),
		//a.ReadString("PQITLWQRPLVTIKIGGQLKEALLDTGADDTVLEEMNLPGRWKPKMIGGIGGFIKVRQYDQILIEICGHKAIGTVLVGPTPVNIIGRNLLTQIGCTLNF"),
		a.ReadString("PISPIETVPVKLKPGMDGPKVKQWPLTEEKIKALVEICTEMEKEGKISKIGPENPYNTPVFAIKKKDSTKWRKLVDFRELNKRTQDFWEVQLGIPHPAGLKKKKSVTVLDVGDAYFSVPLDKDFRKYTAFTIPSINNETPGIRYQYNVLPQGWKGSPAIFQSSMTKILEPFRKQNPDIVIYQYMDDLYVGSDLEIGQHRTKIEELRQHLLRWGFTTPDKKHQKEPPFLWMGYELHPDKWTVQPIVLPEKDSWTVNDIQKLVGKLNWASQIYAGIKVKQLCKLLRGTKALTEVIPLTEEAELELAENREILKEPVHGVYYDPSKDLIAEIQKQGQGQWTYQIYQEPFKNLKTGKYARMRGAHTNDVKQLTEAVQKIATESIVIWGKTPKFKLPIQKETWEAWWTEYWQATWIPEWEFVNTPPLVKLWYQLEKEPIVGAETFYVDGAANRETKLGKAGYVTDRGRQKVVSLTDTTNQKTELQAIHLALQDSGLEVNIVTDSQYALGIIQAQPDKSESELVSQIIEQLIKKEKVYLAWVPAHKGIGGNEQVDKLVSAGIRKVL"),
		scoreHandler,
	)
	cmp.CalcScore()
	return cmp
}

func main() {
	defer profile.Start(profile.CPUProfile).Stop()
	var cmp *alignment.Alignment
	scoreHandler := blosum62.NewBlosum62ScoreHandler(
		/* stopCodonPenalty    */ 5,
		/* gapOpenPenalty      */ 10,
		/* gapExtensionPenalty */ 2,
	)
	start := time.Now()
	for i := 0; i < 10; i++ {
		cmp = test(scoreHandler)
	}
	elapsed := time.Since(start)
	fmt.Printf("Binomial took %s\n", elapsed)
	calculated, all := cmp.GetCalcInfo()
	fmt.Printf("Calculated nodes: %d (%f)\n", calculated, float64(calculated)/float64(all))
	cmp.GetScorePath()
	//table := alignment.GetMutationScoreTable()
	//spew.Print(table)
}
