package hiv2a

import (
	ap "github.com/hivdb/nucamino/alignmentprofile"
	a "github.com/hivdb/nucamino/types/amino"
)

var hiv2APositionalIndelScores = ap.GenePositionalIndelScores{
// "POL": map[int][2]int{
// 	// 85prePR + 99PR = 184
// 	184 + 63:  [2]int{-5, 0},
// 	-184 - 63: [2]int{-5, 0}, // deletion penalty to the far end of RT69
// 	184 + 64:  [2]int{-5, 0},
// 	-184 - 64: [2]int{-5, 0}, // deletion penalty to the far end of RT69
// 	184 + 65:  [2]int{-7, 0},
// 	184 + 66:  [2]int{-7, 0},
// 	184 + 67:  [2]int{-7, 0},
// 	184 + 68:  [2]int{-3, 0},
// 	-184 - 68: [2]int{0, 0},   // remove deletion bonus from RT68/POL223
// 	184 + 69:  [2]int{18, -3}, // group all insertions to RT69/POL224
// 	184 + 70:  [2]int{-3, 0},
// 	184 + 71:  [2]int{-3, 0},
// 	184 + 72:  [2]int{-3, 0},
// 	184 + 73:  [2]int{-3, 0},
// },
}

var (
	// ROD (X05291.1)
	HIV2ASEQ_POL = a.ReadString(`
		TGRFFRTGPLGKEAPQLPRGPSSAGADTNSTPSGSSSGSTGEIYAAREKTERAERETIQGSDRGLTAPRA
		GGDTIQGATNRGLAAPQFSLWKRPVVTAYIEGQPVEVLLDTGADDSIVAGIELGNNYSPKIVGGIGGFIN
		TKEYKNVEIEVLNKKVRATIMTGDTPINIFGRNILTALGMSLNLPVAKVEPIKIMLKPGKDGPKLRQWPL
		TKEKIEALKEICEKMEKEGQLEEAPPTNPYNTPTFAIKKKDKNKWRMLIDFRELNKVTQDFTEIQLGIPH
		PAGLAKKRRITVLDVGDAYFSIPLHEDFRPYTAFTLPSVNNAEPGKRYIYKVLPQGWKGSPAIFQHTMRQ
		VLEPFRKANKDVIIIQYMDDILIASDRTDLEHDRVVLQLKELLNGLGFSTPDEKFQKDPPYHWMGYELWP
		TKWKLQKIQLPQKEIWTVNDIQKLVGVLNWAAQLYPGIKTKHLCRLIRGKMTLTEEVQWTELAEAELEEN
		RIILSQEQEGHYYQEEKELEATVQKDQENQWTYKIHQEEKILKVGKYAKVKNTHTNGIRLLAQVVQKIGK
		EALVIWGRIPKFHLPVEREIWEQWWDNYWQVTWIPDWDFVSTPPLVRLAFNLVGDPIPGAETFYTDGSCN
		RQSKEGKAGYVTDRGKDKVKKLEQTTNQQAELEAFAMALTDSGPKVNIIVDSQYVMGISASQPTESESKI
		VNQIIEEMIKKEAIYVAWVPAHKGIGGNQEVDHLVSQGIRQVLFLEKIEPAQEEHEKYHSNVKELSHKFG
		IPNLVARQIVNSCAQCQQKGEAIHGQVNAELGTWQMDCTHLEGKIIIVAVHVASGFIEAEVIPQESGRQT
		ALFLLKLASRWPITHLHTDNGANFTSQEVKMVAWWIGIEQSFGVPYNPQSQGVVEAMNHHLKNQISRIRE
		QANTIETIVLMAIHCMNFKRRGGIGDMTPSERLINMITTEQEIQFLQAKNSKLKDFRVYFREGRDQLWKG
		PGELLWKGEGAVLVKVGTDIKIIPRRKAKIIRDYGGRQEMDSGSHLEGAREDGEMA
	`) // 85prePR + 99PR + 559RT + 293IN
)

var HIV2ARefLookup = ap.ReferenceSeqs{
	"POL": HIV2ASEQ_POL,
}

var Profile = ap.AlignmentProfile{
	StopCodonPenalty:         4,
	GapOpeningPenalty:        10,
	GapExtensionPenalty:      2,
	IndelCodonOpeningBonus:   0,
	IndelCodonExtensionBonus: 2,
	GeneIndelScores:          hiv2APositionalIndelScores,
	ReferenceSequences:       HIV2ARefLookup,
}
