package hcv4

import (
	ap "github.com/hivdb/nucamino/alignmentprofile"
	a "github.com/hivdb/nucamino/types/amino"
)

var hcv4PositionalIndelScores = ap.GenePositionalIndelScores{}

// HCV4 Reference Sequences; Genebank accession ID: GU814265.1

var (
	HCV4SEQ_NS3 = a.ReadString(`
		APITAYAQQTRGLFSTIVTSLTGRDTNENCGEVQVLSTATQSFLGTAVNGVMWTVYHGAGAKTISGPKGP
		VNQMYTNVDQDLVGWPAPPGVRSLAPCTCGSADLYLVTRHADVIPVRRRGDTRGALLSPRPISTLKGSSG
		GPLLCPMGHAAGIFRAAVCTRGVAKAVDFVPVESLETTMRSPVFTDNSTPPAVPQTYQVAHLHAPTGSGK
		STKVPAAYAAQGYKVLVLNPSVAATLGFGVYMSKAYGIDPNIRSGVRTITTGAPITYSTYGKFLADGGCS
		GGAYDIIICDECHSTDSTTILGIGTVLDQAETAGVRLTVLATATPPGSVTTPHSNIEEVALPTTGEIPFY
		GKAIPLELIKGGRHLIFCHSKKKCDELARQLTSLGLNAVAYYRGLDVSVIPTSGDVVVCATDALMTGFTG
		DFDSVIDCNTSVIQTVDFSLDPTFSIETTTVPQDAVSRSQRRGRTGRGRLGTYRYVTPGERPSGMFDTAV
		LCECYDAGCAWYELTPAETTTRLKAYFDTPGLPVCQDHLEFWESVFTGLTHIDGHFLSQTKQSGENFPYL
		VAYQATVCAKALAPPPSWDTMWKCLIRLKPTLHGPTPLLYRLGSVQNEVVLTHPITKYIMACMSADLEVV
		T
	`)
	HCV4SEQ_NS5A = a.ReadString(`
		AESWLWEVWDWVCTVLSDFKTWLKAKLLPLMPGIPFLSCQRGYKGEWRGDGVMHTTCPCGADLAGHIKNG
		SMRITGPKTCSNTWHGTFPINAYTTGPGVPIPAPNYKFALWRVSAEDYVEVRRVGDFHYVTGVTQDNIKC
		PCQVPAPEFFTEVDGIRLHRHAPKCKPLLRDEVSFSVGLNSFVVGSQLPCEPEPDVAVLTSMLTDPSHIT
		AESARRRLARGSRPSLASSSASQLSAPSLKATCTAPHDSPGTDLLEANLLWGSTATRVETDEKVIILDSF
		ESCVAEPNDDREVSVAAEILRPTKKFPPALPIWARPDYNPPLTETWKQQDYKPPTVHGCALPPGKQPPVP
		PPRRKRTVQLTESVVSTALAELAAKTFGQSEPSSDRDTDLTTPTETTDSGPIVVDDASDDGSYSSMPPLE
		GEPGDPDLTSDSWSTVSGSEDVVCC
	`)
	HCV4SEQ_NS5B = a.ReadString(`
		SMSYSWTGALVTPCAAEESKLPISPLSNSLLRHHNMVYATTTRSAVTRQKKVTFDRLQVVDSHYNEVLKE
		IKARASRVKARLLTTEEACDLTPPHSARSKFGYGAKDVRSHSRKAINHISSVWKDLLDDNNTPIPTTIMA
		KNEVFAVNPAKGGRKPARLIVYPDLGVRVCEKRALHDVIKKLPEAVMGAAYGFQYSPAQRVEFLLTAWKS
		KKTPMGFSYDTRCFDSTVTEKDIRVEEEVYQCCDLEPEARKVITALTDRLYVGGPMHNSKGDLCGYRRCR
		ASGVYTTSFGNTLTCYLKATAAIRAAGLRDCTMLVCGDDLVVIAESDGVEEDNRALRAFTEAMTRYSAPP
		GDAPQPAYDLELITSCSSNVSVAHDVTGKKVYYLTRDPETPLARAAWETVRHTPVNSWLGNIIVYAPTIW
		VRMILMTHFFSILQSQEALEKALDFDMYGVTYSITPLDLPAIIQRLHGLSAFTLHGYSPHELNRVAGALR
		KLGVPPLRAWRHRARAVRAKLIAQGGRAKICGIYLFNWAVKTKLKLTPLPAAAKLDLSGWFTVGAGGGDI
		YHSMSHARPRYLLLCLLLLTVGVGIFLLPAR
	`)
)

var HCV4RefLookup = ap.ReferenceSeqs{
	"NS3":  HCV4SEQ_NS3,
	"NS5A": HCV4SEQ_NS5A,
	"NS5B": HCV4SEQ_NS5B,
}

var Profile = ap.AlignmentProfile{
	StopCodonPenalty:         4,
	GapOpeningPenalty:        10,
	GapExtensionPenalty:      2,
	IndelCodonOpeningBonus:   0,
	IndelCodonExtensionBonus: 2,
	GeneIndelScores:          hcv4PositionalIndelScores,
	ReferenceSequences:       HCV4RefLookup,
}
