package hcv3


import (
	ap "github.com/hivdb/nucamino/alignmentprofile"
	a "github.com/hivdb/nucamino/types/amino"
)

var hcv3PositionalIndelScores = ap.GenePositionalIndelScores{}

// HCV3 Reference Sequences; Genebank accession ID: GU814263.1

var (
	HCV3SEQ_NS3 = a.ReadString(`
		APITAYAQQTRGLLGTIVTSLTGRDKNIVTGEVQVLSTATQTFLGTTVGGVMWTVYHGAGSKTLAGAKHP
		ALQMYTNVDQDLVGWPAPPGAKSLEPCACGSADLYLVTRDADVIPARRRGDSTASLLSPRPLACLKGSSG
		GPVMCPSGHVAGIFRAAVCTRGVAKALQFVPVETLSTQARSPSFSDNSTPPAVPQSYQVGYLHAPTGSGK
		STKVPAAYVAQGYNVLVLNPSVAATLGFGSFMSRAYGIDPNIRTGNRTVTTGAKLTYSTYGKFLADGGCS
		GGAYDVIICDECHAQDATSILGIGTVLDQAETAGVRLTVLATATPPGSITVPHSNIEEVALGSEGEIPFY
		GKAIPIALLKGGRHLIFCHSKKKCDEVAAKLRGMGLNAVAYYRGLDVSVIPTTGDVVVCATDALMTGFTG
		DFDSVIDCNVAVEQYVDFSLDPTFSIETRTAPQDAVSRSQRRGRTGRGRLGTYRYVAPGERPSGMFDSVV
		LCECYDAGCSWYDLQPAETTVRLRAYLNTPGLPVCQDHLDFWESVFTGLTHIDAHFLSQTKQQGLNFSFL
		TAYQATVCARAQASPPSWDETWKCLVRLKPTLHGPTPLLYRLGPVQNDICLTHPVTKYIMACMSADLEVT
		T
`)
	HCV3SEQ_NS5A = a.ReadString(`
		SGDWLRDIWDWVCSVLSDFKTWLSAKIMPALPGLPFISCQKGYKGVWRGDGVMSTRCPCGASITGHVKNG
		SMRLAGPRMCANMWHGTFPINEYTTGPSTPCPSPNYTRALWRVAASSYVEVRRVGDFHYITGATEDELKC
		PCQVPAAEFFTEVDGVRLHRYAPPCKPLLREEITFSVGLHSYAIGSQLPCEPEPDVSVLTSMLRDPSHIT
		AETAARRLARGSPPSEASSSASQLSAPSLKATCQTHRPHPDAELVDANLLWRQEMGSNITRVESETKVVI
		LDSFEPLRAEADDAELSVAAECFKKPPKYPPALPIWARPDYNPPLLDRWKAPDYVPPTVHGCALPPRGAP
		PVPPPRRKRTIQLDGSNVSAALAALAEKSFPTPKSQEENSSSSGVDTQSSTTSRMPPSPGGESDSESCSS
		MPPLEGEPGDPDLSCDSWSTVSDNEEQSVVCC
	`)
	HCV3SEQ_NS5B = a.ReadString(`
		SMSYSWTGALITPCSAEEEKLPISPLSNSLLRHHNLVYSTSSRSASQRQRKVTFDRLQVLDDHYKTALKE
		VKERASRVKARMLTIEEACALVPPHSARSKFGYSAKDVRSLSSRAIDQIRSVWEDLLEDTTTPIPTTIMA
		KNEVFCVDPAKGGRKPARLIVYPDLGVRVCEKRALYDVIQKLSIETMGSAYGFQYSPQQRVERLLKMWTS
		KKTPLGFSYDTRCFDSTVTEQDIRVEEEIYQCCNLEPEARKVISSLTERLYCGGPMFNSKGAQCGYRRCR
		ASGVLPTSFGNTITCYIKATAAAKAAGLRNPDFLVCGDDLVVVAESDGVDEDRAALRAFTEAMTRYSAPP
		GDAPQPTYDLELITSCSSNVSVARDDKGRRYYYLTRDATTPLARAAWETARHTPVNSWLGNIIMYAPTIW
		VRMVMMTHFFSILQSQEILDRPLDFEMYGATYSVTPLDLPAIIERLHGLSAFTLHSYSPVELNRVAGTLR
		KLGCPPLRAWRHRARAVRAKLIAQGGKAKICGLYLFNWAVRTKTNLTPLPATGQLDLSSWFTVGVGGNDI
		YHSVSRARTRHLLLCLLLLTVGVGIFLLPAR
	`)
)

var HCV3RefLookup = ap.ReferenceSeqs{
	"NS3":  HCV3SEQ_NS3,
	"NS5A": HCV3SEQ_NS5A,
	"NS5B": HCV3SEQ_NS5B,
}

var Profile = ap.AlignmentProfile{
	StopCodonPenalty:         4,
	GapOpeningPenalty:        10,
	GapExtensionPenalty:      2,
	IndelCodonOpeningBonus:   0,
	IndelCodonExtensionBonus: 2,
	GeneIndelScores:          hcv3PositionalIndelScores,
	ReferenceSequences:       HCV3RefLookup,
}
