package hcv1b

import (
	ap "github.com/hivdb/nucamino/alignmentprofile"
	a "github.com/hivdb/nucamino/types/amino"
)

var hcv1bPositionalIndelScores = ap.GenePositionalIndelScores{}

// HCV1B Reference Sequences; Genebank accession ID: AJ238799.1

var (
	HCV1BSEQ_NS3 = a.ReadString(`
		APITAYSQQTRGLLGCIITSLTGRDRNQVEGEVQVVSTATQSFLATCVNGVCWTVYHGAGSKTLAGPKGP
		ITQMYTNVDQDLVGWQAPPGARSLTPCTCGSSDLYLVTRHADVIPVRRRGDSRGSLLSPRPVSYLKGSSG
		GPLLCPSGHAVGIFRAAVCTRGVAKAVDFVPVESMETTMRSPVFTDNSSPPAVPQTFQVAHLHAPTGSGK
		STKVPAAYAAQGYKVLVLNPSVAATLGFGAYMSKAHGIDPNIRTGVRTITTGAPITYSTYGKFLADGGCS
		GGAYDIIICDECHSTDSTTILGIGTVLDQAETAGARLVVLATATPPGSVTVPHPNIEEVALSSTGEIPFY
		GKAIPIETIKGGRHLIFCHSKKKCDELAAKLSGLGLNAVAYYRGLDVSVIPTSGDVIVVATDALMTGFTG
		DFDSVIDCNTCVTQTVDFSLDPTFTIETTTVPQDAVSRSQRRGRTGRGRMGIYRFVTPGERPSGMFDSSV
		LCECYDAGCAWYELTPAETSVRLRAYLNTPGLPVCQDHLEFWESVFTGLTHIDAHFLSQTKQAGDNFPYL
		VAYQATVCARAQAPPPSWDQMWKCLIRLKPTLHGPTPLLYRLGAVQNEVTTTHPITKYIMACMSADLEVV
		T
	`)
	HCV1BSEQ_NS5A = a.ReadString(`
		SGSWLRDVWDWICTVLTDFKTWLQSKLLPRLPGVPFFSCQRGYKGVWRGDGIMQTTCPCGAQITGHVKNG
		SMRIVGPRTCSNTWHGTFPINAYTTGPCTPSPAPNYSRALWRVAAEEYVEVTRVGDFHYVTGMTTDNVKC
		PCQVPAPEFFTEVDGVRLHRYAPACKPLLREEVTFLVGLNQYLVGSQLPCEPEPDVAVLTSMLTDPSHIT
		AETAKRRLARGSPPSLASSSASQLSAPSLKATCTTRHDSPDADLIEANLLWRQEMGGNITRVESENKVVI
		LDSFEPLQAEEDEREVSVPAEILRRSRKFPRAMPIWARPDYNPPLLESWKDPDYVPPVVHGCPLPPAKAP
		PIPPPRRKRTVVLSESTVSSALAELATKTFGSSESSAVDSGTATASPDQPSDDGDAGSDVESYSSMPPLE
		GEPGDPDLSDGSWSTVSEEASEDVVCC
	`)
	HCV1BSEQ_NS5B = a.ReadString(`
		SMSYTWTGALITPCAAEETKLPINALSNSLLRHHNLVYATTSRSASLRQKKVTFDRLQVLDDHYRDVLKE
		MKAKASTVKAKLLSVEEACKLTPPHSARSKFGYGAKDVRNLSSKAVNHIRSVWKDLLEDTETPIDTTIMA
		KNEVFCVQPEKGGRKPARLIVFPDLGVRVCEKMALYDVVSTLPQAVMGSSYGFQYSPGQRVEFLVNAWKA
		KKCPMGFAYDTRCFDSTVTENDIRVEESIYQCCDLAPEARQAIRSLTERLYIGGPLTNSKGQNCGYRRCR
		ASGVLTTSCGNTLTCYLKAAAACRAAKLQDCTMLVCGDDLVVICESAGTQEDEASLRAFTEAMTRYSAPP
		GDPPKPEYDLELITSCSSNVSVAHDASGKRVYYLTRDPTTPLARAAWETARHTPVNSWLGNIIMYAPTLW
		ARMILMTHFFSILLAQEQLEKALDCQIYGACYSIEPLDLPQIIQRLHGLSAFSLHSYSPGEINRVASCLR
		KLGVPPLRVWRHRARSVRARLLSQGGRAATCGKYLFNWAVRTKLKLTPIPAASQLDLSSWFVAGYSGGDI
		YHSLSRARPRWFMWCLLLLSVGVGIYLLPNR
	`)
)

var HCV1BRefLookup = ap.ReferenceSeqs{
	"NS3":  HCV1BSEQ_NS3,
	"NS5A": HCV1BSEQ_NS5A,
	"NS5B": HCV1BSEQ_NS5B,
}

var Profile = ap.AlignmentProfile{
	StopCodonPenalty:         4,
	GapOpeningPenalty:        10,
	GapExtensionPenalty:      2,
	IndelCodonOpeningBonus:   0,
	IndelCodonExtensionBonus: 2,
	GeneIndelScores:          hcv1bPositionalIndelScores,
	ReferenceSequences:       HCV1BRefLookup,
}
