package hiv2b

import (
	ap "github.com/hivdb/nucamino/alignmentprofile"
	a "github.com/hivdb/nucamino/types/amino"
)

var hiv2BPositionalIndelScores = ap.GenePositionalIndelScores{
// "POL": map[int][2]int{
// 	// 84prePR + 99PR = 183
// 	183 + 63:  [2]int{-5, 0},
// 	-183 - 63: [2]int{-5, 0}, // deletion penalty to the far end of RT69
// 	183 + 64:  [2]int{-5, 0},
// 	-183 - 64: [2]int{-5, 0}, // deletion penalty to the far end of RT69
// 	183 + 65:  [2]int{-7, 0},
// 	183 + 66:  [2]int{-7, 0},
// 	183 + 67:  [2]int{-7, 0},
// 	183 + 68:  [2]int{-3, 0},
// 	-183 - 68: [2]int{0, 0},   // remove deletion bonus from RT68/POL223
// 	183 + 69:  [2]int{18, -3}, // group all insertions to RT69/POL224
// 	183 + 70:  [2]int{-3, 0},
// 	183 + 71:  [2]int{-3, 0},
// 	183 + 72:  [2]int{-3, 0},
// 	183 + 73:  [2]int{-3, 0},
// },
}

var (
	// EHO (U27200.1)
	HIV2BSEQ_POL = a.ReadString(`
		TGGFFRVRPLGKEASQFPRPGTPGDSAICAPDEPSIRHDTSGCDSICTPCRSSRGDAKELHATREEAEGE
		QRETLQGGDRGFAAPQFSLWRRPVVKATIEGQSVEVLLDTGADDSIVAGIELGSNYTPKIVGGIGGFINT
		NEYKNVEIEVVGKRVRATVMTGDTPINIFGRNILNSLGMTLNFPVARIEPVKVQLKPEKDGPKIRQWPLS
		KEKILALKEICEKMEKEGQLEEAPPTNPYNSPTFAIKKKDKNKWRMLIDFRELNKVTQEFTEVQLGIPHP
		AGLASKKRITVLDVGDAYFSVPLDPDFRQYTAFTLPAVNNAEPGKRYLYKVLPQGWKGSPAIFQYTMAKV
		LDPFRKANNDVTIIQYMDDILVASDRSDLEHDRVVSQLKELLNNMGFSTPEEKFQKDPPFKWMGYELWPK
		KWKLQKIQLPEKEVWTVNDIQKLVGVLNWAAQLFPGIKTRHICKLIRGKMTLTEEVQWTELAEAEFQENK
		IILEQEQEGSYYKEGVPLEATVQKNLANQWTYKIHQGDKILKVGKYAKVKNTHTNGVRLLAHVVQKIGKE
		ALVIWGEIPMFHLPVERETWDQWWTDYWQVTWIPEWDFVSTPPLIRLAYNLVKDPLEGVETYYTDGSCNK
		ASKEGKAGYVTDRGKDKVKPLEQTTNQQAELEAFALALQDSGPQVNIIVDSQYVMGIVAAQPTETESPIV
		REIIEEMIKKEKIYVGWVPAHKGLGGNQEVDHLVSQGIRQILFLEKIEPAQEEHEKYHNNVKELVHKFGI
		PQLVARQIVNSCDKCQQKGEAIHGQVNSELGTWQMDCTHLEGKVIIVAVHVASGFIEAEVIPQETGRQTA
		LFLLKLASRWPITHLHTDNGANFTSQDVKMAAWWIGIEQTFGVPYNPESQGVVEAMNHHLKNQIDRIRDQ
		AVSIETVVLMATHCMNFKRRGGIGDMTPAERIVNMITTEQEIQFLQTKNLKFQNFRVYYREGRDQLWKGP
		GDLLWKGEGAVIIKVGTEIKVIPRRKAKIIRNYGGGKELDCSADVEDTMQAREVAQSN
	`) // 84prePR + 99PR + 559RT + 296IN
)

var HIV2BRefLookup = ap.ReferenceSeqs{
	"POL": HIV2BSEQ_POL,
}

var Profile = ap.AlignmentProfile{
	StopCodonPenalty:         4,
	GapOpeningPenalty:        10,
	GapExtensionPenalty:      2,
	IndelCodonOpeningBonus:   0,
	IndelCodonExtensionBonus: 2,
	GeneIndelScores:          hiv2BPositionalIndelScores,
	ReferenceSequences:       HIV2BRefLookup,
}
