package hcv6

import (
	ap "github.com/hivdb/nucamino/alignmentprofile"
	a "github.com/hivdb/nucamino/types/amino"
)

var hcv6PositionalIndelScores = ap.GenePositionalIndelScores{}

// HCV6 Reference Sequences; Genebank accession ID: AF064490.1

var (
	HCV6SEQ_NS3 = a.ReadString(`
		APITAYAQQTRGLVGTIVTSLTGRDKNEVEGEVQVVSTDTQSFVATSINGVMWTVYHGPGFKTLAGPKGP
		VCQMYTNVDLDLVGWPSPPGARSLTPCNCGSSDLYLVTREADVIPARRRGDSRAALLSPRPISTLKGSSG
		GPIMCPSGHVVGLFRAAVCTRGVAKSLDFIPVENMETTMRSPSFTDNSTPPAVPQTYQVGYLHAPTGSGK
		STRVPAAYASQGYKVLVLNPSVAATLSFGSYMRQAYGVEPNIRTGVRTVTTGGAITYSTYGEFLADGGCS
		GGAYDIIICDECHSTDPTTVLGVGTVLDQAETAGVRLTVLPTATPPGSVTVPHPNITETALPTTGEIPFY
		GKAIPLEYIKGGRHLIFCHSKKKCDELAGKLKSLGLNAVAFYRGVDVSVIPTSGDVVVCATDALMTGYTG
		DFDSVIDCNVAVTQVVDFSLDPTFSIETTTVPQDAVSRSQRRGRTGRGKPGVYRFVSQGERPSGMFDTVV
		LCEAYDTGCAWYELTPSETTVRLRAYMNTPGLPVCQDHLEFWEGVFTGLTHIDAHFLSHTKQAGENFAYL
		VAYQATVCARAKAPPPSWDMMWKCLIRLKPTLTGPTPLLYRLGAVQNGVITTHPITKYIMTCMSADLEVI
		T
	`)
	HCV6SEQ_NS5A = a.ReadString(`
		ATSWLRDVWDWVCTVLSDFKVWLQAKLFPRLPGIPFLSCQAGYRGVWAGDGVCHTTCTCGAVIAGHVKNG
		TMKITGPKTCSNTWHGTFPINATTTGPSTPRPAPNYQRALWRVSAEDYVEVRRLGDCHYVVGVTAEGLKC
		PCQVPAPEFFTEVDGVRIHRYAPPCKPLLRDEVTFSVGLSNYAVGSQLPCEPEPDVTVVTSMLTDPTHIT
		AETAARRLKKGSPPSLASSSANQLSAPSLRATCTTSQKHPEMELLQANLLWKHEMGSHIPRVQSENKVVV
		LDSFELYPLEYEEREISVSVECHRQPRCKFPPVFPVWARPDNNPPFIQAWQMPGYEPPVVSGCAVAPPKP
		APVPPPRRKRLVHLDESTVSHALAQLADKVFVESSNDPGPSSDSGLSITSPVPPDPTTPEDAGSEAESYS
		SMPPLEGEPGDPDLSSGSWSTVSDEDDVVCC
	`)
	HCV6SEQ_NS5B = a.ReadString(`
		SMSYSWTGALITPCAAEEEKLPINPLSNSLVRHHNMVYSTTSRSASLRQKKVTFDRVQVFDQHYQDVLKE
		IKLRASTVQAKLLSIEEACDLTPSHSARSKYGYGAQDVRSRASKAVDHIPSVWEGLLEDSDTPIPTTIMA
		KNEVFCVDPSKGGRKPARLIVYPDLGVRVCEKMALYDVTQKLPQAVMGPAYGFQYSPNQRVEYLLKMWRS
		KKVPMGFSYDTRCFDSTVTERDIRTENDIYQSCQLDPVARRVVSSLTERLYVGGPMANSKGQSCGYRRCR
		ASGVLPTSMGNTLTCYLKAQAACRAANIKDCDMLVCGDDLVVICESAGVQEDTASLRAFTDAMTRYSAPP
		GDAPQPTYDLELITSCSSNVSVAHEGNGKKYYYLTRDCTTPLARAAWETARHTPVNSWLGNIIMFAPTIW
		VRMVLMNHFFSILQSQEQLEKAFDFDIYGVTYSVSPLDLPAIIQRLHGMAAFSLHGYSPVELNRVGACLR
		KLGVLPSRAWRHRARAVRAKLIAQGGKAAICGKYLFNWAVKTKLKLTPLVSASKLDLSGWFVAGYDGGDI
		YHSVSQARPRFLLLGLLLLTVGVGIFLLPAR
	`)
)

var HCV6RefLookup = ap.ReferenceSeqs{
	"NS3":  HCV6SEQ_NS3,
	"NS5A": HCV6SEQ_NS5A,
	"NS5B": HCV6SEQ_NS5B,
}

var Profile = ap.AlignmentProfile{
	StopCodonPenalty:         4,
	GapOpeningPenalty:        10,
	GapExtensionPenalty:      2,
	IndelCodonOpeningBonus:   0,
	IndelCodonExtensionBonus: 2,
	GeneIndelScores:          hcv6PositionalIndelScores,
	ReferenceSequences:       HCV6RefLookup,
}
